# Generated by Django 2.2 on 2019-10-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20191014_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='time',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='<django.db.models.query_utils.DeferredAttribute object at 0x0488E8D0><django.db.models.query_utils.DeferredAttribute object at 0x0488E8F0>/profileimage/'),
        ),
    ]
