# Generated by Django 2.2 on 2019-10-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20191014_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage/'),
        ),
    ]
