# Generated by Django 2.2 on 2019-10-23 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0005_auto_20191022_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='watch.Videos')),
            ],
        ),
    ]
