# Generated by Django 2.2 on 2019-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0008_auto_20191031_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumpnail',
            field=models.ImageField(null=True, upload_to='thumbnail/'),
        ),
    ]
