# Generated by Django 2.2 on 2019-11-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0009_videos_thumpnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='thumpnail',
            new_name='thumbnail',
        ),
    ]
