# Generated by Django 2.2 on 2019-11-27 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0011_youtube'),
    ]

    operations = [
        migrations.DeleteModel(
            name='youtube',
        ),
    ]
